name: Cross-Account Sync

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC3点（北京时间11点）
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Shanghai
    
    steps:
      - name: 检出源代码
        uses: actions/checkout@v4
        
      - name: 验证权限
        run: |
          if [ -z "$TARGET_PAT" ]; then
            echo "::error::未检测到TARGET_PAT"
            exit 1
          fi
          echo "✅ 权限验证通过"
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
          
      - name: 执行同步脚本
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          chmod +x small-packages.sh
          ./small-packages.sh 2>&1 | tee sync.log
          
      - name: 上传日志
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sync-logs
          path: |
            sync.log
            sync_temp/target_repo/.git/logs/*
          retention-days: 3
