name: Sync

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点（北京时间11点）
  workflow_dispatch:     # 手动触发选项

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          sparse-checkout: none  # 禁用稀疏检出
          fetch-depth: 0

      - name: Run Sync Script
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}  # 目标账户PAT
        run: |
          chmod +x clone.sh
          ./clone.sh

      - name: Upload Logs
        if: always()  # 确保失败时也能上传日志
        uses: actions/upload-artifact@v4  # 升级到最新稳定版
        with:
          name: sync-logs
          path: |
            sync_temp/target_repo/.git/logs/HEAD
            sync_temp/target_repo/.git/logs/refs/**
          retention-days: 3  # 自动清理旧日志
          compression-level: 9  # 最高压缩率
