name: Auto Sync

on:
  schedule:
    - cron: '0 3 * * *'  # UTC时间每天3点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PAT
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          if [ -z "$TARGET_PAT" ]; then
            echo "::error::未检测到TARGET_PAT"
            exit 1
          fi
          echo "✅ PAT有效性验证通过"

      - name: Run Sync
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          chmod +x small-packages.sh
          ./small-packages.sh 2>&1 | tee sync.log

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sync-logs
          path: |
            sync.log
            sync_temp/target_repo/.git/logs/*
