name: Auto Sync

on:
  schedule:
    - cron: '0 3 * * *'  # UTC时间每天3点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Sync
        env:
          TARGET_PAT: ${{ secrets.TARGET_PAT }}
        run: |
          chmod +x small-packages.sh
          ./small-packages.sh
          
      - name: Clean Workspace
        if: always()
        run: rm -rf sync_workspace
